name: GitHub Actions Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      # Step 1: obtenemos codigo fuente
      - name: Checkout source code
        uses: actions/checkout@v2

      # Step 2: creamos venv e instalamos dependencias
      - name: install dependencies
        run: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt

      # Step 3: ejecutamos linters y flake8 y lanzamos casos de prueba 
      - name: run tests
        run: |
            source venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v

